# Generated by Django 2.2.1 on 2019-07-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190709_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='issued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book_info',
            name='no_of_copies',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_info',
            name='book_title',
            field=models.CharField(max_length=60),
        ),
    ]
