# Generated by Django 2.2.1 on 2019-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190710_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=80)),
                ('book_author', models.CharField(max_length=60)),
                ('comment', models.TextField()),
            ],
        ),
    ]
